name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push query
        uses: docker/build-push-action@v2
        with:
          context: ./query-api/
          push: true
          tags: antonioalmeidab/query-api:latest
      -
        name: Build and push patient
        uses: docker/build-push-action@v2
        with:
          context: ./patient-api/
          push: true
          tags: antonioalmeidab/patient-api:latest
      -
        name: Build and push disease
        uses: docker/build-push-action@v2
        with:
          context: ./disease-api/
          push: true
          tags: antonioalmeidab/disease-api:latest
        
